# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:

- stage: Build
  jobs:
  - job: Build
    steps:
    - task: SomeTask

- stage: DeployTest
  jobs:
  - deployment: DeployTest
    displayName: Deploy to test
    environment: Test

- stage: DeployUAT
  jobs:
  - deployment: DeployUAT
    displayName: Deploy to UAT
    environment: UAT